version: '3'
services:
  web:
    image: afaraldo/millionaires:latest
    restart: unless-stopped
    command: bash -c "rm -f tmp/pids/server.pid && rake assets:precompile && rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "yes"

  worker:
    image: afaraldo/millionaires:latest
    restart: unless-stopped
    command: bash -c "rm -f tmp/pids/server.pid && good_job start"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      RAILS_ENV: production

  proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config: