version: '3'
services:
  web:
    image: afaraldo/millionaires:latest
    command: bash -c "rm -f tmp/pids/server.pid && rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "yes"
      http_proxy: "http://proxy:80"
      HTTPS_PROXY: "https://proxy:443"
      NO_PROXY: "localhost,127.0.0.1,.newrelic.com,.googleapis.com,.google.com"

  proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
